"""r PAR L'ANNULATION DES TADPOLES — le calcul cloture. 07/08/2026.
Conventions standard (Polchinski) : 2k^2 = (2pi)^7 l_s^8 g_s^2 ; T_p = (2pi)^{-p} l_s^{-(p+1)}/g_s."""
import numpy as np
hbar_c=1.97327e-16   # m.GeV
print("="*76); print("1. LES DEUX CONFIGURATIONS ET CE QUE LES TADPOLES IMPOSENT")
print("="*76)
print("  Type I' sur S1/Z2 : 16 D8 (charge +1 chacune) + 2 O8 (charge -8 chacun). Total = 0 ✓")
print("  BPS => tension = |charge| :")
print("   (a) SYMETRIQUE (8 D8 a chaque bord) : a chaque bord 8 - 8 = 0")
print("       => tension locale NULLE et charge enfermee NULLE => F0 = 0 dans le bulk")
print("       => AUCUNE SOURCE, AUCUN PUITS. Le CDD ne peut pas y vivre.")
print("   (b) ASYMETRIQUE (16 D8 au bord y=0, bord lointain = O8 seul) :")
print("       y=0 : 16 - 8 = +8 (tension locale NON NULLE) ; y=piR : -8 ; F0 = 8 unites")
print("       => c'est LA SEULE configuration qui produit un puits.")
print("  >>> LA PREDICTION DE SON ARTICLE I (paroi lointaine sans Modele Standard)")
print("      N'EST PAS UN CHOIX : ELLE EST REQUISE POUR QUE LE CADRE EXISTE. ✓")
print("\n"+"="*76); print("2. r = (energie de flux) / (tension nette), EN FORME CLOSE")
print("="*76)
print("  saut de F0 par unite de charge : Delta F0 = c * k^2 T_8   (c = O(1), convention)")
print("  densite d'energie de flux = F0^2/(4k^2) ; integree sur piR")
print("  tension nette au bord = 8 T_8 e^{-phi} = 8 T_8/g_s")
print("  k^2 T_8 = [(2pi)^7 l_s^8 g_s^2/2] x [(2pi)^-8 l_s^-9/g_s] = g_s/(4 pi l_s)")
print("  =>  r = 2 c^2 k^2 T_8 (piR) g_s = c^2 g_s^2 R/(2 l_s)      [forme close]")
print("\n"+"="*76); print("3. LE NOMBRE — avec SES parametres verrouilles")
print("="*76)
print(f"  {'M_s (GeV)':>10} {'l_s (m)':>10} {'R/l_s':>10} {'r (c=1, F0=8)':>15} {'r (F0=1)':>12}")
for Ms in (0.8e8,2.0e8,3.6e8):
    ls=hbar_c/Ms; gs=0.010; R=8.2e-6
    r8=gs**2*R/(2*ls); r1=r8/64
    print(f"  {Ms:10.1e} {ls:10.2e} {R/ls:10.2e} {r8:15.2e} {r1:12.2e}")
print(f"\n  CIBLE : r dans [0,149 ; 0,419]")
print("  OBTENU : r ~ 1e12 a 1e15 pour F0 = 1 unite, ~1e14 a 1e16 pour F0 = 8.")
print("  >>> ECART DE 13 A 16 ORDRES. Et F0 est QUANTIFIE : la seule valeur plus petite")
print("      que 1 unite est ZERO, qui donne r = 0 donc c_b = 0.")
print("\n"+"="*76); print("4. LE VERDICT, ET SA ROBUSTESSE")
print("="*76)
print("  c_b(r->0) = 0        (pas de couplage : la RAR disparait)")
print("  c_b(r>>1) -> 1,193   (2 fois trop fort)")
print("  la fenetre [0,30;0,61] exige r ~ 0,25 : ENTRE LES DEUX, ET INACCESSIBLE.")
print("  ROBUSTESSE : la constante de convention c entre en c^2 ; il faudrait c ~ 1e-8")
print("  pour sauver la fenetre. Aucune convention ne deplace un resultat de 16 ordres.")
print("  CAUSE PHYSIQUE : l'intervalle du CDD fait ~1e19 longueurs de corde. Toute masse")
print("  de Romans non nulle y depose une energie de vide colossale. La IIA massive et")
print("  un intervalle mesoscopique sont INCOMPATIBLES — independamment du CDD.")
